/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uit.view;

import com.uitprojects.is210.employee.Employee;
import uit.controllers.LoginController;

/**
 *
 * @author quochuy
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public AdminFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void showListEmp() {
        menuListEmpActionPerformed(null);
    }

    public void showEditEmpPane(Employee employee) {
        AddEmpPane pane = new AddEmpPane(this, employee);
        tpnBoard.addTab("Chỉnh sửa nhân viên", pane);
        tpnBoard.setSelectedComponent(pane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        tpnBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        tbrCloseCurrentTab = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tbrEmpManagement = new javax.swing.JButton();
        tbrListEmp = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbrBillManagement = new javax.swing.JButton();
        tbrListBill = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tbrMembershipManagement = new javax.swing.JButton();
        tbrListMembership = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        tbrPromotionManagement = new javax.swing.JButton();
        tbrListPromotion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuChangePassword = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuEmpManagement = new javax.swing.JMenu();
        menuAddEmp = new javax.swing.JMenuItem();
        menuListEmp = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuBillManagement = new javax.swing.JMenuItem();
        menuListBill = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuMembershipManagement = new javax.swing.JMenuItem();
        menuListMembership = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý siêu thị");
        setSize(new java.awt.Dimension(1080, 768));

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 768));
        jPanel1.setSize(new java.awt.Dimension(1080, 768));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tpnBoard.addTab("Home", jPanel1);

        jScrollPane1.setAutoscrolls(true);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        tbrCloseCurrentTab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrCloseCurrentTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close_32.png"))); // NOI18N
        tbrCloseCurrentTab.setText("Đóng tab hiện tại");
        tbrCloseCurrentTab.setFocusable(false);
        tbrCloseCurrentTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrCloseCurrentTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrCloseCurrentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrCloseCurrentTabActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrCloseCurrentTab);
        jToolBar1.add(jSeparator2);

        tbrEmpManagement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrEmpManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/employee_32.png"))); // NOI18N
        tbrEmpManagement.setText("Quản lý nhân viên");
        tbrEmpManagement.setFocusable(false);
        tbrEmpManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrEmpManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrEmpManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrEmpManagementActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrEmpManagement);

        tbrListEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrListEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_32.png"))); // NOI18N
        tbrListEmp.setText("Danh sách nhân viên");
        tbrListEmp.setFocusable(false);
        tbrListEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListEmpActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListEmp);
        jToolBar1.add(jSeparator4);

        tbrBillManagement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrBillManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bill_32.png"))); // NOI18N
        tbrBillManagement.setText("Quản lý hoá đơn");
        tbrBillManagement.setFocusable(false);
        tbrBillManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrBillManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrBillManagementActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrBillManagement);

        tbrListBill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrListBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_bill_32.png"))); // NOI18N
        tbrListBill.setText("Danh sách hoá đơn");
        tbrListBill.setFocusable(false);
        tbrListBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListBill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListBillActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListBill);
        jToolBar1.add(jSeparator3);

        tbrMembershipManagement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrMembershipManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/membership_card_32.png"))); // NOI18N
        tbrMembershipManagement.setText("Quản lý Membership");
        tbrMembershipManagement.setFocusable(false);
        tbrMembershipManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrMembershipManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrMembershipManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrMembershipManagementActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrMembershipManagement);

        tbrListMembership.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrListMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_membership_32.png"))); // NOI18N
        tbrListMembership.setText("Danh sách Membership");
        tbrListMembership.setFocusable(false);
        tbrListMembership.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListMembership.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListMembershipActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListMembership);
        jToolBar1.add(jSeparator5);

        tbrPromotionManagement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrPromotionManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/promotion_32.png"))); // NOI18N
        tbrPromotionManagement.setText("Quản lý chương trình khuyến mãi");
        tbrPromotionManagement.setFocusable(false);
        tbrPromotionManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrPromotionManagement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrPromotionManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrPromotionManagementActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrPromotionManagement);

        tbrListPromotion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbrListPromotion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_promotion_32.png"))); // NOI18N
        tbrListPromotion.setText("Danh sách chương trình khuyến mãi");
        tbrListPromotion.setActionCommand("Danh sách chương trình khuyến mãi");
        tbrListPromotion.setFocusable(false);
        tbrListPromotion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListPromotion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListPromotionActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListPromotion);

        jScrollPane1.setViewportView(jToolBar1);

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        menuFile.setText("File");

        menuChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/change_password_16.png"))); // NOI18N
        menuChangePassword.setText("Đổi mật khẩu");
        menuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePasswordActionPerformed(evt);
            }
        });
        menuFile.add(menuChangePassword);
        menuFile.add(jSeparator1);

        menuExit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit_16.png"))); // NOI18N
        menuExit.setText("Đăng xuất / Thoát");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuView.setText("View");

        menuEmpManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/employee_16.png"))); // NOI18N
        menuEmpManagement.setText("Nhân viên");
        menuEmpManagement.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        menuAddEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add_emp_16.png"))); // NOI18N
        menuAddEmp.setText("Quản lý nhân viên");
        menuAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddEmpActionPerformed(evt);
            }
        });
        menuEmpManagement.add(menuAddEmp);

        menuListEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_16.png"))); // NOI18N
        menuListEmp.setText("Danh sách nhân viên");
        menuListEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListEmpActionPerformed(evt);
            }
        });
        menuEmpManagement.add(menuListEmp);

        menuView.add(menuEmpManagement);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bill_16.png"))); // NOI18N
        jMenu1.setText("Hoá đơn");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        menuBillManagement.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        menuBillManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bill_16.png"))); // NOI18N
        menuBillManagement.setText("Quản lý hoá đơn");
        menuBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBillManagementActionPerformed(evt);
            }
        });
        jMenu1.add(menuBillManagement);

        menuListBill.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        menuListBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_bill_16.png"))); // NOI18N
        menuListBill.setText("Danh sách hoá đơn");
        menuListBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListBillActionPerformed(evt);
            }
        });
        jMenu1.add(menuListBill);

        menuView.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/membership_card_16.png"))); // NOI18N
        jMenu2.setText("Membership");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        menuMembershipManagement.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        menuMembershipManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/membership_card_16.png"))); // NOI18N
        menuMembershipManagement.setText("Quản lý Membership");
        menuMembershipManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMembershipManagementActionPerformed(evt);
            }
        });
        jMenu2.add(menuMembershipManagement);

        menuListMembership.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        menuListMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_membership_16.png"))); // NOI18N
        menuListMembership.setText("Danh sách Membership");
        menuListMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListMembershipActionPerformed(evt);
            }
        });
        jMenu2.add(menuListMembership);

        menuView.add(jMenu2);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/promotion_16.png"))); // NOI18N
        jMenu7.setText("Chương trình khuyến mãi");
        jMenu7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/promotion_16.png"))); // NOI18N
        jMenuItem1.setText("Quản lý chương trình khuyến mãi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/list_promotion_16.png"))); // NOI18N
        jMenuItem2.setText("Danh sách chương trình khuyến mãi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        menuView.add(jMenu7);

        jMenuBar1.add(menuView);

        menuHelp.setText("Help");

        jMenuItem4.setText("Về chúng tôi");
        menuHelp.add(jMenuItem4);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpnBoard)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbrCloseCurrentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrCloseCurrentTabActionPerformed
        int selectedIndex = tpnBoard.getSelectedIndex();
        if(selectedIndex > 0) {
            tpnBoard.remove(selectedIndex);
        }
    }//GEN-LAST:event_tbrCloseCurrentTabActionPerformed

    private void menuAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddEmpActionPerformed
        AddEmpPane pane = new AddEmpPane(this);
        tpnBoard.addTab("Quản lý nhân viên", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_menuAddEmpActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuListEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListEmpActionPerformed
        ListEmpPane pane = new ListEmpPane(this);
        tpnBoard.addTab("Danh sách nhân viên", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_menuListEmpActionPerformed

    private void tbrEmpManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrEmpManagementActionPerformed
        menuAddEmpActionPerformed(evt);
    }//GEN-LAST:event_tbrEmpManagementActionPerformed

    private void tbrListEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListEmpActionPerformed
        menuListEmpActionPerformed(evt);
    }//GEN-LAST:event_tbrListEmpActionPerformed

    private void tbrBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrBillManagementActionPerformed
        BillManagementPane pane = new BillManagementPane(this);
        tpnBoard.addTab("Quản lý hoá đơn", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrBillManagementActionPerformed

    private void menuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePasswordActionPerformed
        ChangePasswordDialog dialog = new ChangePasswordDialog(null, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuChangePasswordActionPerformed

    private void tbrListBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListBillActionPerformed
        ListBillPane pane = new ListBillPane(this);
        tpnBoard.addTab("Danh sách hoá đơn", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListBillActionPerformed

    private void menuListBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListBillActionPerformed
        tbrListBillActionPerformed(evt);
    }//GEN-LAST:event_menuListBillActionPerformed

    private void menuBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBillManagementActionPerformed
        tbrBillManagementActionPerformed(evt);
    }//GEN-LAST:event_menuBillManagementActionPerformed

    private void menuListMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListMembershipActionPerformed
        tbrListMembershipActionPerformed(evt);
    }//GEN-LAST:event_menuListMembershipActionPerformed

    private void menuMembershipManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMembershipManagementActionPerformed
        tbrMembershipManagementActionPerformed(evt);
    }//GEN-LAST:event_menuMembershipManagementActionPerformed

    private void tbrMembershipManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrMembershipManagementActionPerformed
        MembershipManagementPane pane = new MembershipManagementPane(this);
        tpnBoard.addTab("Quản lý thẻ thành viên", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrMembershipManagementActionPerformed

    private void tbrListMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListMembershipActionPerformed
        ListMembershipPane pane = new ListMembershipPane(this);
        tpnBoard.addTab("Danh sách thẻ thành viên", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListMembershipActionPerformed

    private void tbrPromotionManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrPromotionManagementActionPerformed
        PromotionManagementPane pane = new PromotionManagementPane(this);
        tpnBoard.addTab("Quản lý chương trình khuyến mãi", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrPromotionManagementActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tbrListPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListPromotionActionPerformed
        ListPromotionPane pane = new ListPromotionPane(this);
        tpnBoard.addTab("Danh sách chương trình khuyến mãi", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListPromotionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
//                new LoginController(new LoginFrame());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAddEmp;
    private javax.swing.JMenuItem menuBillManagement;
    private javax.swing.JMenuItem menuChangePassword;
    private javax.swing.JMenu menuEmpManagement;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuListBill;
    private javax.swing.JMenuItem menuListEmp;
    private javax.swing.JMenuItem menuListMembership;
    private javax.swing.JMenuItem menuMembershipManagement;
    private javax.swing.JMenu menuView;
    private javax.swing.JButton tbrBillManagement;
    private javax.swing.JButton tbrCloseCurrentTab;
    private javax.swing.JButton tbrEmpManagement;
    private javax.swing.JButton tbrListBill;
    private javax.swing.JButton tbrListEmp;
    private javax.swing.JButton tbrListMembership;
    private javax.swing.JButton tbrListPromotion;
    private javax.swing.JButton tbrMembershipManagement;
    private javax.swing.JButton tbrPromotionManagement;
    private javax.swing.JTabbedPane tpnBoard;
    // End of variables declaration//GEN-END:variables
}
